USE ProcessoDB
GO



SELECT u.NOME, u.LOGIN, u.EMAIL
FROM USUARIO U
    INNER JOIN OPERACAO_USUARIO OU
        ON OU.ID_USUARIO = U.ID_USUARIO
GROUP BY U.NOME, U.LOGIN, U.EMAIL
HAVING COUNT(OU.ID_OPERACAO_ACESSO) > 5 